name: bmed360v2020
dependencies:
- python = 3.7
# - conda-forge::cartopy
- conda-forge::geoplot
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- descartes
- geopandas
- geojson
- git
- imageio
- ipykernel
- ipython
- ipywidgets
- jupyter
- matplotlib
# - mplleaflet
- numpy
- pandas
- plotly
- pip
- scikit-image
- scikit-learn
- scipy
- seaborn
- pip:
  - cufflinks
  - pip
  - kaggle
  - xlrd
  - eli5
  - pdpbox
  - nibabel
  - nilearn
  - dipy
  - pyradiomics
  - opencv-python
  # - pandas-profiling
  - SimpleITK
